### ISSUE TITLE
Component never drawn

### ISSUE THREAD

**Issue by thibbo** [andreluisjunqueira/react-native-documentscanner-android#12]
Hi, 
I imported your library into my project and somehow, I couldn't manage to get it work. I followed the steps described in the README and yet, no luck. I had to update support library version and compileSdkVersion to match those of my project. 
So far, I can implement your component but it doesn't display anything.
Any thoughts ?

**Comment by trostinsky** [comment]
I've the same problem... All okay, without errors, but component isn't visible.

**Comment by trostinsky** [comment]
Okay, I'm solved this problem added some styles to DocumentScanner. Your should do same.
For example maker _View_  with _height: 100%, width: 100%_ and inner it adding DocumentScanner with same styles (width, height = 100%). I hope it will help you.

**Comment by thibbo** [comment]
> 
> 
> Okay, I'm solved this problem added some styles to DocumentScanner. Your should do same.
> For example maker _View_ with _height: 100%, width: 100%_ and inner it adding DocumentScanner with same styles (width, height = 100%). I hope it will help you.

Thanks a lot

**Comment by saturnim** [comment]
@trostinsky could you share final style you applied. I have black screen.

**Comment by zahidahmed024** [comment]
pls share the code. :'(

**Comment by SwagatRanjit84** [comment]
@zahidahmed024  Email id?

**Comment by trostinsky** [comment]
> @trostinsky could you share final style you applied. I have black screen.

Yes, sorry, I receive email only today. Styles for DocumentScanner(I used styled-components): 

```
const Wrapper = styled.View`
  width: 100%;
  height: 100%;
  background-color:#dcdcdc;
  justify-content: flex-start;
  position:relative;
`;

const Scanner = styled(DocumentScanner)`
  height: 100%;
  width: 100%;
`;
```
