### ISSUE TITLE
Auto detect not working in my application

### ISSUE THREAD

**Issue by Manojdreams** [andreluisjunqueira/react-native-documentscanner-android#35]
My code:

<DocumentScanner style={{ flex: 1, backgroundColor: 'transparent', width: '100%', height: '100%', }}
          onPictureTaken={data => {
            console.log(data.path);
          }}
          enableTorch={false}
          manualOnly={false}
          detectionCountBeforeCapture={5} />

**Comment by visw227** [comment]
Hi, I'm facing the same issue. I see you closed this issue. How did you fix it? The auto detect works sometimes and it doesnot most of the times. Any clue?

**Comment by Manojdreams** [comment]
Hi, Actually I faced this issue due to the background of the document. When
we scan a document with white background the scanner fails to detect it. So
I closed that issue.

Regards,
Manoj Kumar G.
